name: Release Tag test
on:
  workflow_dispatch:
  
jobs:
  tag-dms-image:
    name: Release Tag DMS Image
    runs-on: ubuntu-latest
    steps:
      - name: Prepare Release Tags
        id: prepare-tags
        run: |
          IMAGE_NAME="edfialliance/data-management-service"
          MAJOR_TAG="0.4.0"
          MINOR_TAG=`echo $MAJOR_TAG | cut -d '.' -f 1,2`
          PRE_IMAGE="${IMAGE_NAME}:dms-pre-${MAJOR_TAG}"
          RELEASE_MAJOR="${IMAGE_NAME}:${MAJOR_TAG}"
          RELEASE_MINOR="${IMAGE_NAME}:${MINOR_TAG}"

          echo "PRE_IMAGE=$PRE_IMAGE" >> $GITHUB_OUTPUT
          echo "RELEASE_MAJOR=$RELEASE_MAJOR" >> $GITHUB_OUTPUT
          echo "RELEASE_MINOR=$RELEASE_MINOR" >> $GITHUB_OUTPUT

      - name: Pull DMS Prerelease Image
        run: docker pull "${{ steps.prepare-tags.outputs.PRE_IMAGE }}"

      - name: Tag DMS image
        run: |
          docker tag "${{ steps.prepare-tags.outputs.PRE_IMAGE }}" "${{ steps.prepare-tags.outputs.RELEASE_MAJOR }}"
          docker tag "${{ steps.prepare-tags.outputs.PRE_IMAGE }}" "${{ steps.prepare-tags.outputs.RELEASE_MINOR }}"

      - name: List Images
        run: docker image list
